In [61]:
import pandas as pd
import os
import requests
from bs4 import BeautifulSoup

In [2]:
dfs = pd.read_html("https://fbref.com/en/squads/18bb7c10/Arsenal-Stats")

In [3]:
pl_2022_2023_links = {
    "Arsenal": "https://fbref.com/en/squads/18bb7c10/Arsenal-Stats",
    "Manchester_City": "https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats",
    "Manchester_United": "https://fbref.com/en/squads/19538871/Manchester-United-Stats",
    "Newcastle_United": "https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats",
    "Tottenham": "https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats",
    "Brighton": "https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats",
    "Brentford": "https://fbref.com/en/squads/cd051869/Brentford-Stats",
    "Fulham": "https://fbref.com/en/squads/fd962109/Fulham-Stats",
    "Chelsea": "https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats",
    "Liverpool": "https://fbref.com/en/squads/822bd0ba/Liverpool-Stats",
    "Aston_Villa": "https://fbref.com/en/squads/8602292d/Aston-Villa-Stats",
    "Crystal_Palance": "https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats",
    "Forest": "https://fbref.com/en/squads/e4a775cb/Nottingham-Forest-Stats",
    "Leicester": "https://fbref.com/en/squads/a2d435b3/Leicester-City-Stats",
    "Wolves": "https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats",
    "West_Ham": "https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats",
    "Leeds": "https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats",
    "Everton": "https://fbref.com/en/squads/d3fd31cc/Everton-Stats",
    "Bournemouth": "https://fbref.com/en/squads/4ba7cbea/Bournemouth-Stats",
    "Southampton": "https://fbref.com/en/squads/33c895d4/Southampton-Stats",
}

df_order = [
    "overall",
    "fixtures",
    "gk",
    "advanced_gk",
    "shooting",
    "passing",
    "pass_types",
    "goal_and_shot_creation",
    "defensive_actions",
    "possession",
    "playing_time",
    "miscellaneous_tasks",
    "overall_regular_season",
    "home_away_regular_season",
]

In [167]:
for club in pl_2022_2023_links:
    current_club = club
    df_list = pd.read_html(pl_2022_2023_links[current_club])
    for i, df in enumerate(df_list):
        if not os.path.isdir(f"pl_data/{current_club}/"):
            os.makedirs(f"pl_data/{current_club}/")
        df.to_csv(f"pl_data/{current_club}/{df_order[i]}.csv", index=False)

### Acquiring specific team data

In [4]:
headers = {'User-Agent': 
           'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36'}

page = "https://www.transfermarkt.us/fulham-fc/kader/verein/931/saison_id/2022/plus/1"
pageTree = requests.get(page, headers=headers)
pageSoup = BeautifulSoup(pageTree.content, 'html.parser')

In [5]:
names = []
positions = []
tables= pageSoup.find_all('table', class_='inline-table')
for table in tables:
    rows = table.find_all('tr')
    name = rows[0].text.strip()
    position = rows[1].text.strip()
    names.append(name)
    positions.append(position)

In [6]:
player_prices = pageSoup.find_all(class_='rechts hauptlink')
prices = []
for price in player_prices:
    price = price.text.strip()
    prices.append(price)

In [7]:
info = pd.DataFrame({'name': names, 'price': prices, 'position':positions})

In [8]:
report = []

tables= pageSoup.find_all('table', class_='items')
for table in tables:
    rows = table.find_all('td', {"class": "zentriert"})
    for i in range(len(rows)):
        report.append(rows[i])

general = [report[i:i + 8] for i in range(0, len(report), 8)]
overall = []
for g in general:
     overall.append(dict(
         dob = g[1].text.strip(),
         nationality = g[2].img['alt'],
         height = g[3].text.strip(),
         foot = g[4].text.strip(),
         join_date = g[5].text.strip(),
         contract_expiration = g[7].text.strip(), 
     )
    )

In [9]:
info2 = pd.DataFrame(overall)

In [10]:
overall = pd.concat([info, info2], axis=1)

In [11]:
overall

,name,price,position,dob,nationality,height,foot,join_date,contract_expiration
0,Bernd Leno,€10.00m,Goalkeeper,"Mar 4, 1992 (30)",Germany,"1,90m",right,"Aug 2, 2022","Jun 30, 2025"
1,Marek Rodak,€3.50m,Goalkeeper,"Dec 13, 1996 (26)",Slovakia,"1,94m",right,"Jul 1, 2019","Jun 30, 2024"
2,Tosin Adarabioyo,€18.00m,Centre-Back,"Sep 24, 1997 (25)",England,"1,96m",right,"Oct 5, 2020","Jun 30, 2024"
3,Issa Diop,€15.00m,Centre-Back,"Jan 9, 1997 (26)",France,"1,94m",right,"Aug 10, 2022","Jun 30, 2027"
4,Shane Duffy,€2.50m,Centre-Back,"Jan 1, 1992 (31)",Ireland,"1,93m",right,"Jan 31, 2023","Jun 30, 2023"
5,Tim Ream,€1.00m,Centre-Back,"Oct 5, 1987 (35)",United States,"1,86m",left,"Aug 20, 2015","Jun 30, 2024"
6,Antonee Robinson,€10.00m,Left-Back,"Aug 8, 1997 (25)",United States,"1,83m",left,"Aug 20, 2020","Jun 30, 2024"
7,Layvin Kurzawa,€5.00m,Left-Back,"Sep 4, 1992 (30)",France,"1,82m",left,"Sep 1, 2022","Jun 30, 2023"
8,Kenny Tete,€7.00m,Right-Back,"Oct 9, 1995 (27)",Netherlands,"1,80m",right,"Sep 10, 2020","Jun 30, 2024"
9,Kevin Mbabu,€7.00m,Right-Back,"Apr 19, 1995 (27)",Switzerland,"1,84m",right,"Jul 27, 2022","Jun 30, 2025"
10,Cédric Soares,€4.00m,Right-Back,"Aug 31, 1991 (31)",Portugal,"1,71m",right,"Jan 31, 2023","Jun 30, 2023"
11,João Palhinha,€28.00m,Defensive Midfield,"Jul 9, 1995 (27)",Portugal,"1,90m",right,"Jul 4, 2022","Jun 30, 2027"
12,Harrison Reed,€15.00m,Central Midfield,"Jan 27, 1995 (28)",England,"1,81m",right,"Aug 30, 2020","Jun 30, 2024"
13,Sasa Lukic,€13.00m,Central Midfield,"Aug 13, 1996 (26)",Serbia,"1,83m",right,"Jan 31, 2023","Jun 30, 2027"
14,Tom Cairney,€2.00m,Central Midfield,"Jan 20, 1991 (32)",Scotland,"1,85m",left,"Jul 1, 2015","Jun 30, 2024"
15,Tyrese Francois,€500k,Central Midfield,"Jul 16, 2000 (22)",Australia,"1,73m",left,"Jul 1, 2021","Jun 30, 2024"
16,Andreas Pereira,€13.00m,Attacking Midfield,"Jan 1, 1996 (27)",Brazil,"1,78m",right,"Jul 11, 2022","Jun 30, 2026"
17,Bobby De Cordova-Reid,€7.00m,Attacking Midfield,"Feb 2, 1993 (30)",Jamaica,"1,70m",right,"Jan 24, 2020","Jun 30, 2024"
18,Manor Solomon,€18.00m,Left Winger,"Jul 24, 1999 (23)",Israel,"1,70m",right,"Jul 25, 2022","Jun 30, 2023"
19,Neeskens Kebano,€4.00m,Left Winger,"Mar 10, 1992 (30)",DR Congo,"1,70m",right,"Aug 26, 2016","Jun 30, 2023"
20,Willian,€3.00m,Left Winger,"Aug 9, 1988 (34)",Brazil,"1,75m",right,"Sep 1, 2022","Jun 30, 2023"
21,Harry Wilson,€17.00m,Right Winger,"Mar 22, 1997 (25)",Wales,"1,73m",left,"Jul 24, 2021","Jun 30, 2026"
22,Daniel James,€16.00m,Right Winger,"Nov 10, 1997 (25)",Wales,"1,71m",right,"Sep 1, 2022","May 31, 2023"
23,Aleksandar Mitrović,€28.00m,Centre-Forward,"Sep 16, 1994 (28)",Serbia,"1,89m",right,"Jul 30, 2018","Jun 30, 2026"
24,Carlos Vinícius,€5.00m,Centre-Forward,"Mar 25, 1995 (27)",Brazil,"1,90m",left,"Sep 1, 2022","Jun 30, 2025"

## Advanced GK

In [222]:
advanced_gk = pd.read_csv("pl_data/Fulham/advanced_gk.csv", header=1)

In [223]:
advanced_gk = advanced_gk.iloc[:-2]

In [224]:
advanced_gk.columns

Index(['Player', 'Nation', 'Pos', 'Age', '90s', 'GA', 'PKA', 'FK', 'CK', 'OG',
       'PSxG', 'PSxG/SoT', 'PSxG+/-', '/90', 'Cmp', 'Att', 'Cmp%', 'Att.1',
       'Thr', 'Launch%', 'AvgLen', 'Att.2', 'Launch%.1', 'AvgLen.1', 'Opp',
       'Stp', 'Stp%', '#OPA', '#OPA/90', 'AvgDist', 'Matches'],
      dtype='object')

In [225]:
advanced_gk.drop(columns=[
    '90s',
    'Matches',
    'Nation',
    'Pos',
    'Age',
    'PKA', 
    'FK', 
    'CK', 
    'OG', 
    'PSxG', 
    'PSxG/SoT',
    '/90',
    'Cmp', 
    'Att', 
    'Opp',
    'Stp', 
    '#OPA/90',
    'AvgDist'], inplace=True)

In [226]:
advanced_gk.rename(columns={
    'GA': 'goals_allowed',
    'Cmp%': 'launched_pass_completion',
    'Att.1': 'attempted_passes',
    'Thr': 'attempted_throws',
    'Launch%': 'percentage_launched_passes',
    'AvgLen': 'average_pass_length',
    'Att.2': 'goal_kicks_attempted',
    'Launch%.1': 'launched_goal_kicks',
    'AvgLen.1': 'average_goal_kick_length',
    'Stp%': '%_stopped_crosses',
    '#OPA': 'actions_outside_pk'}, inplace=True)

In [227]:
advanced_gk

,Player,goals_allowed,PSxG+/-,launched_pass_completion,attempted_passes,attempted_throws,percentage_launched_passes,average_pass_length,goal_kicks_attempted,launched_goal_kicks,average_goal_kick_length,%_stopped_crosses,actions_outside_pk
0,Bernd Leno,28,4.1,35.3,592,107,30.9,31.1,139,41.7,37.1,8.6,27
1,Marek Rodák,2,0.0,34.0,46,3,73.9,46.0,15,86.7,60.0,3.8,2

## Defensive Actions

In [228]:
defensive_actions = pd.read_csv("pl_data/Fulham/defensive_actions.csv", header=1)

In [229]:
defensive_actions = defensive_actions.iloc[:-2]

In [230]:
defensive_actions.drop(columns=[
    '90s',
    'Matches',
    'Nation',
    'Pos',
    'Age',
    'Tkl.1',
    'Att',
    'Tkl%',
    'Lost',
    'Blocks',
    'Tkl+Int'], inplace=True)

In [231]:
defensive_actions.rename(columns={
    'Tkl': 'tackles',
    'TklW': 'tackles_won',
    'Def 3rd': 'defensive_third_tackles',
    'Mid 3rd': 'midfield_tackles',
    'Att 3rd': 'attacking_third_tackles',
    'Sh': 'shots_blocked',
    'Pass': 'passes_blocked',
    'Int': 'interceptions',
    'Clr': 'clearances',
    'Err': 'errors_leading_to_goal'}, inplace=True)

In [232]:
defensive_actions.head()

,Player,tackles,tackles_won,defensive_third_tackles,midfield_tackles,attacking_third_tackles,shots_blocked,passes_blocked,interceptions,clearances,errors_leading_to_goal
0,Tim Ream,21,11,10,8,3,19,13,32,74,0
1,Andreas Pereira,11,6,1,4,6,3,15,4,5,0
2,João Palhinha,98,56,33,44,21,4,28,27,41,1
3,Bobby Reid,29,19,8,9,12,3,18,13,25,0
4,Harrison Reed,22,15,7,13,2,4,27,13,26,0

## GK

In [233]:
gk = pd.read_csv("pl_data/Fulham/gk.csv", header=1)

In [234]:
gk = gk.iloc[:-2]

In [235]:
gk.drop(columns=[
    'MP',
    'Starts',
    'Min',
    '90s',
    'Matches',
    'Nation',
    'Pos',
    'Age',
    'GA',
    'GA90',
    'Save%',
    'W',
    'D',
    'L',
    'CS%',
    'PKm',
    'Save%.1'], inplace=True)

In [236]:
gk.rename(columns={
    'SoTA': 'shots_on_target_against',
    'Saves': 'saves',
    'CS': 'clean_sheets',
    'PKatt': 'penalties_faced',
    'PKA': 'penalties_conceded',
    'PKsv': 'penalties_saved',}, inplace=True)

In [237]:
gk.head()

,Player,shots_on_target_against,saves,clean_sheets,penalties_faced,penalties_conceded,penalties_saved
0,Bernd Leno,111,83,5,3,3,0
1,Marek Rodák,4,2,1,0,0,0

## Goal and Shot Creation

In [238]:
goal_and_shot = pd.read_csv("pl_data/Fulham/goal_and_shot_creation.csv", header=1)

In [239]:
goal_and_shot = goal_and_shot.iloc[:-2]

In [240]:
goal_and_shot.drop(columns=[
    '90s',
    'Matches',
    'Nation',
    'Pos',
    'Age',
    'SCA90',
    'GCA90',
    ], inplace=True)

In [241]:
goal_and_shot.rename(columns={
    'SCA': 'shot_creating_actions',
    'PassLive': 'sca_live_passes',
    'PassDead': 'sca_dead_passes',
    'TO': 'sca_take_ons',
    'Sh': 'sca_shots',
    'Fld': 'sca_fouls_drawn',
    'Def': 'sca_defensive_actions',
    'GCA': 'goal_creation_actions',
    'PassLive.1': 'gca_live_passes',
    'PassDead.1': 'gca_dead_passes',
    'TO.1': 'gca_take_ons',
    'Sh.1': 'gca_shots',
    'Fld.1': 'gca_fouls_drawn',
    'Def.1': 'gca_defensive_actions',
    }, inplace=True)

In [242]:
goal_and_shot.head()

,Player,shot_creating_actions,sca_live_passes,sca_dead_passes,sca_take_ons,sca_shots,sca_fouls_drawn,sca_defensive_actions,goal_creation_actions,gca_live_passes,gca_dead_passes,gca_take_ons,gca_shots,gca_fouls_drawn,gca_defensive_actions
0,Tim Ream,17,17,0,0,0,0,0,0,0,0,0,0,0,0
1,Andreas Pereira,76,33,35,0,4,4,0,7,2,5,0,0,0,0
2,João Palhinha,18,12,0,0,2,0,4,0,0,0,0,0,0,0
3,Bobby Reid,40,25,1,2,3,7,2,2,1,0,0,0,0,1
4,Harrison Reed,41,35,2,2,1,1,0,3,2,0,1,0,0,0

## Misc

In [243]:
misc = pd.read_csv("pl_data/Fulham/miscellaneous_tasks.csv", header=1)

In [244]:
misc = misc.iloc[:-2]

In [245]:
misc.drop(columns=[
    '90s',
    'Matches',
    'Nation',
    'Pos',
    'Age',
    '2CrdY',
    'Crs',
    'Int',
    'TklW',
    'Won%',
    ], inplace=True)

In [246]:
misc.rename(columns={
    'CrdY': 'yellow_cards',
    'CrdR': 'red_cards',
    'Fls': 'fouls',
    'Fld': 'fouls_drawn',
    'Off': 'offsides',
    'Fls': 'fouls',
    'Fld': 'fouls_drawn',
    'Off': 'offsides',
    'PKwon': 'penalties_won',
    'PKcon': 'penalties_conceded',
    'OG': 'own_goals',
    'Recov': 'ball_recoveries',
    'Won': 'aerial_duels_won',
    'Lost': 'aerial_duels_lost',
    
    }, inplace=True)

In [247]:
misc.head()

,Player,yellow_cards,red_cards,fouls,fouls_drawn,offsides,penalties_won,penalties_conceded,own_goals,ball_recoveries,aerial_duels_won,aerial_duels_lost
0,Tim Ream,2,0,11,5,1,0,0,0,131,29,18
1,Andreas Pereira,6,0,28,23,2,0,1,0,84,7,19
2,João Palhinha,8,0,25,26,1,0,0,0,125,42,25
3,Bobby Reid,7,0,29,14,6,2,1,0,99,9,26
4,Harrison Reed,5,0,19,13,2,0,0,0,96,19,22

## Passing

In [248]:
passing = pd.read_csv("pl_data/Fulham/passing.csv", header=1)

In [249]:
passing = passing.iloc[:-2]

In [250]:
passing.drop(columns=[
    '90s',
    'Matches',
    'Nation',
    'Pos',
    'Age',
    'Cmp',
    'Att',
    'Cmp%',
    'TotDist',
    'PrgDist',
    'Cmp%.1',
    'Cmp%.2',
    'Cmp%.3',
    'xAG',
    'A-xAG',
    ], inplace=True)

In [251]:
passing.rename(columns={
    'CrdY': 'yellow_cards',
    'CrdR': 'red_cards',
    'Fls': 'fouls',
    'Fld': 'fouls_drawn',
    'Off': 'offsides',
    'Fls': 'fouls',
    'Fld': 'fouls_drawn',
    'Off': 'offsides',
    'PKwon': 'penalties_won',
    'PKcon': 'penalties_conceded',
    'OG': 'own_goals',
    'Recov': 'ball_recoveries',
    'Won': 'aerial_duels_won',
    'Lost': 'aerial_duels_lost',
    'Cmp.1': 'short_passes_completed',
    'Att.1': 'short_passes_attempted',
    'Cmp.2': 'medium_passes_completed',
    'Att.2': 'medium_passes_attempted',
    'Cmp.3': 'long_passes_completed',
    'Att.3': 'long_passes_attempted',
    'Ast': 'assists',
    'xA': 'expected_assists',
    'KP': 'key_passes',
    '1/3': 'passes_into_final_third',
    'PPA': 'passes_into_penalty_box',
    'CrsPA': 'crosses_into_pentalty_area',
    'PrgP': 'progressive_passes',
    }, inplace=True)

In [252]:
passing.head()

,Player,short_passes_completed,short_passes_attempted,medium_passes_completed,medium_passes_attempted,long_passes_completed,long_passes_attempted,assists,expected_assists,key_passes,passes_into_final_third,passes_into_penalty_box,crosses_into_pentalty_area,progressive_passes
0,Tim Ream,253,292,631,680,181,256,0,0.2,0,81,0,0,75
1,Andreas Pereira,219,279,154,213,75,163,5,3.1,48,56,17,9,76
2,João Palhinha,291,338,227,266,61,89,0,0.2,3,74,2,0,63
3,Bobby Reid,254,314,172,238,25,64,1,0.9,13,27,23,7,43
4,Harrison Reed,304,361,179,219,41,77,1,1.0,20,48,18,7,56

## Playing Time

In [253]:
playing_time = pd.read_csv("pl_data/Fulham/playing_time.csv", header=1)

In [254]:
playing_time = playing_time.iloc[:-2]

In [255]:
playing_time = playing_time[['Player', 'Min', 'MP', 'Starts']]

In [256]:
playing_time.head()

            Player     Min  MP  Starts
0         Tim Ream  1977.0  22      22
1  Andreas Pereira  1815.0  22      22
2    João Palhinha  1865.0  21      21
3       Bobby Reid  1733.0  21      21
4    Harrison Reed  1725.0  21      21

## Possession

In [257]:
possession = pd.read_csv("pl_data/Fulham/possession.csv", header=1)

In [258]:
possession = possession.iloc[:-2]

In [259]:
possession.drop(columns=[
    '90s',
    'Matches',
    'Nation',
    'Pos',
    'Age',
    'Touches',
    'Live',
    'Succ%',
    'Tkld%',
    'Rec',
    'PrgR',
    ], inplace=True)

In [260]:
possession.rename(columns={
    'Def Pen': 'touches_penalty_area_defending',
    'Def 3rd': 'touches_defensive_third',
    'Mid 3rd': 'touches_middle_third',
    'Att 3rd': 'touches_attacking_third',
    'Att Pen': 'touches_penality_area_attacking',
    'Att': 'attempted_take_ons',
    'Succ': 'successful_take-ons',
    'Tkld': 'tackled_take-ons',
    'Carries': 'carries',
    'TotDist': 'total_carrying_distance',
    'PrgDist': 'progressive_carrying_distance',
    'PrgC': 'progressive_carries',
    '1/3': 'carries_into_final_third',
    'CPA': 'carries_into_pentalty_area',
    'Mis': 'carry_miscontrols',
    'Dis': 'carry_dispossessions',
    }, inplace=True)

In [261]:
possession.head()

,Player,touches_penalty_area_defending,touches_defensive_third,touches_middle_third,touches_attacking_third,touches_penality_area_attacking,attempted_take_ons,successful_take-ons,tackled_take-ons,carries,total_carrying_distance,progressive_carrying_distance,progressive_carries,carries_into_final_third,carries_into_pentalty_area,carry_miscontrols,carry_dispossessions
0,Tim Ream,204,748,648,49,12,9,6,1,870,4842,3277,18,8,0,12,3
1,Andreas Pereira,12,68,410,417,40,33,9,19,476,2644,1187,37,30,8,39,33
2,João Palhinha,50,241,629,157,26,19,6,9,451,1630,541,4,8,2,21,16
3,Bobby Reid,46,186,362,366,52,32,10,16,480,2255,1105,40,28,11,41,23
4,Harrison Reed,35,163,505,259,25,17,6,11,417,1908,676,19,16,1,29,14

## Shooting

In [262]:
shooting = pd.read_csv("pl_data/Fulham/shooting.csv", header=1)

In [263]:
shooting = shooting.iloc[:-2]

In [264]:
shooting.drop(columns=[
    '90s',
    'Matches',
    'Nation',
    'Pos',
    'Age',
    'SoT%',
    'Sh/90',
    'SoT/90',
    'G/SoT',
    'npxG',
    'npxG/Sh',
    'G-xG',
    'np:G-xG',
    ], inplace=True)

In [265]:
shooting.rename(columns={
    'Gls': 'goals',
    'Sh': 'total_shots',
    'SoT': 'shots_on_target',
    'G/Sh': 'goals_per_shot',
    'Dist': 'average_shot_distance',
    'FK': 'freekick_shots',
    'PK': 'penalty_kicks_converted',
    'PKatt': 'penality_kicks_attempted',
    }, inplace=True)

In [266]:
shooting.head()

,Player,goals,total_shots,shots_on_target,goals_per_shot,average_shot_distance,freekick_shots,penalty_kicks_converted,penality_kicks_attempted,xG
0,Tim Ream,1,3,2,0.33,9.8,0,0,0,0.3
1,Andreas Pereira,2,28,11,0.04,21.9,8,1,1,3.5
2,João Palhinha,3,27,7,0.11,16.7,0,0,0,2.0
3,Bobby Reid,4,23,9,0.17,12.8,0,0,0,3.4
4,Harrison Reed,2,15,4,0.13,20.3,0,0,0,1.3

In [267]:
dfs = [
    advanced_gk,
    defensive_actions,
    gk,
    goal_and_shot,
    misc,
    passing,
    playing_time,
    possession,
    shooting,
]

In [268]:
from functools import reduce

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Player'],
                                            how='outer'), dfs)

In [269]:
pd.merge(df_merged, overall, left_on='Player', right_on='name').drop('name', axis=1).to_csv('sample_dataset.csv', index=False)